# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a589dea304e246ad6ccfb7df3a7292895d1a0f05f581ba6659cc48ba9f8a60d808f73c034c1d8b3939124ec662d376e96479e45b6ca3c0e51a9eeb92b9936518

test:
  secret_key_base: d548a2cadbc1a209cc2bd176fdc7e77775617ef0c3cc41cf291ea34eb7370517bfac4c2cd8943fc95051b72ec610c2129948de740e320e7af580394c3e9b746e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
